// Code generated by mockery v2.14.1. DO NOT EDIT.

package biz

import (
	contextx "github.com/blackhorseya/irent/pkg/contextx"
	billingmodel "github.com/blackhorseya/irent/pkg/entity/domain/billing/model"

	mock "github.com/stretchr/testify/mock"

	model "github.com/blackhorseya/irent/pkg/entity/domain/account/model"
)

// MockIBiz is an autogenerated mock type for the IBiz type
type MockIBiz struct {
	mock.Mock
}

// GetArrears provides a mock function with given fields: ctx, from
func (_m *MockIBiz) GetArrears(ctx contextx.Contextx, from *model.Profile) (*billingmodel.Arrears, error) {
	ret := _m.Called(ctx, from)

	var r0 *billingmodel.Arrears
	if rf, ok := ret.Get(0).(func(contextx.Contextx, *model.Profile) *billingmodel.Arrears); ok {
		r0 = rf(ctx, from)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billingmodel.Arrears)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, *model.Profile) error); ok {
		r1 = rf(ctx, from)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Liveness provides a mock function with given fields: ctx
func (_m *MockIBiz) Liveness(ctx contextx.Contextx) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(contextx.Contextx) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Readiness provides a mock function with given fields: ctx
func (_m *MockIBiz) Readiness(ctx contextx.Contextx) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(contextx.Contextx) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockIBiz interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockIBiz creates a new instance of MockIBiz. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockIBiz(t mockConstructorTestingTNewMockIBiz) *MockIBiz {
	mock := &MockIBiz{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
