service: sion

frameworkVersion: '3'
configValidationMode: error

plugins:
  - serverless-go-plugin

custom:
  go:
    baseDir: . # folder where go.mod file lives, if set `handler` property should be set relatively to that folder
    binDir: bin # target folder for binary files
    cgo: 0 # CGO_ENABLED flag
    cmd: 'GOARCH=amd64 GOOS=linux go build -ldflags="-s -w"' # compile command
    monorepo: false # if enabled, builds function every directory (useful for monorepo where go.mod is managed by each function
    supportedRuntimes: [ "provided.al2023" ] # the plugin compiles a function only if runtime is declared here (either on function or provider level)
    buildProvidedRuntimeAsBootstrap: true # if enabled, builds and archive function with only single "bootstrap" binary (useful for runtimes like provided.al2)

provider:
  name: aws
  runtime: provided.al2023
  stage: ${opt:stage, 'prod'}
  region: ap-northeast-3

package:
  individually: true

functions:
  restful:
    handler: ./adapter/lambda/
    name: ${sls:stage}-${self:service}-restful
    events:
      - http: ANY /{proxy+}
    environment: ${file(./deployments/${opt:stage, 'prod'}/.env.yaml)}

  fetchAvailableCars:
    handler: ./adapter/jobs/fetchAvailableCars/
    name: ${sls:stage}-${self:service}-fetchAvailableCars
    events:
      - schedule: rate(1 minute)
    environment: ${file(./deployments/${opt:stage, 'prod'}/.env.yaml)}

