// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.9
// source: domain/billing/model/arrears.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArrearsRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderNo     string `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	TotalAmount int64  `protobuf:"varint,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
}

func (x *ArrearsRecord) Reset() {
	*x = ArrearsRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_billing_model_arrears_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArrearsRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrearsRecord) ProtoMessage() {}

func (x *ArrearsRecord) ProtoReflect() protoreflect.Message {
	mi := &file_domain_billing_model_arrears_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrearsRecord.ProtoReflect.Descriptor instead.
func (*ArrearsRecord) Descriptor() ([]byte, []int) {
	return file_domain_billing_model_arrears_proto_rawDescGZIP(), []int{0}
}

func (x *ArrearsRecord) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *ArrearsRecord) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type Arrears struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records     []*ArrearsRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	TotalAmount int64            `protobuf:"varint,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
}

func (x *Arrears) Reset() {
	*x = Arrears{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_billing_model_arrears_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Arrears) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arrears) ProtoMessage() {}

func (x *Arrears) ProtoReflect() protoreflect.Message {
	mi := &file_domain_billing_model_arrears_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arrears.ProtoReflect.Descriptor instead.
func (*Arrears) Descriptor() ([]byte, []int) {
	return file_domain_billing_model_arrears_proto_rawDescGZIP(), []int{1}
}

func (x *Arrears) GetRecords() []*ArrearsRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *Arrears) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

var File_domain_billing_model_arrears_proto protoreflect.FileDescriptor

var file_domain_billing_model_arrears_proto_rawDesc = []byte{
	0x0a, 0x22, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67,
	0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x61, 0x72, 0x72, 0x65, 0x61, 0x72, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x22, 0x4d, 0x0a,
	0x0d, 0x41, 0x72, 0x72, 0x65, 0x61, 0x72, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x5e, 0x0a, 0x07,
	0x41, 0x72, 0x72, 0x65, 0x61, 0x72, 0x73, 0x12, 0x30, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x69, 0x6c, 0x6c, 0x69,
	0x6e, 0x67, 0x2e, 0x41, 0x72, 0x72, 0x65, 0x61, 0x72, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x3f, 0x5a, 0x3d,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6c, 0x61, 0x63, 0x6b,
	0x68, 0x6f, 0x72, 0x73, 0x65, 0x79, 0x61, 0x2f, 0x69, 0x72, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f,
	0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_domain_billing_model_arrears_proto_rawDescOnce sync.Once
	file_domain_billing_model_arrears_proto_rawDescData = file_domain_billing_model_arrears_proto_rawDesc
)

func file_domain_billing_model_arrears_proto_rawDescGZIP() []byte {
	file_domain_billing_model_arrears_proto_rawDescOnce.Do(func() {
		file_domain_billing_model_arrears_proto_rawDescData = protoimpl.X.CompressGZIP(file_domain_billing_model_arrears_proto_rawDescData)
	})
	return file_domain_billing_model_arrears_proto_rawDescData
}

var file_domain_billing_model_arrears_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_domain_billing_model_arrears_proto_goTypes = []interface{}{
	(*ArrearsRecord)(nil), // 0: billing.ArrearsRecord
	(*Arrears)(nil),       // 1: billing.Arrears
}
var file_domain_billing_model_arrears_proto_depIdxs = []int32{
	0, // 0: billing.Arrears.records:type_name -> billing.ArrearsRecord
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_domain_billing_model_arrears_proto_init() }
func file_domain_billing_model_arrears_proto_init() {
	if File_domain_billing_model_arrears_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_domain_billing_model_arrears_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArrearsRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_billing_model_arrears_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Arrears); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_domain_billing_model_arrears_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_billing_model_arrears_proto_goTypes,
		DependencyIndexes: file_domain_billing_model_arrears_proto_depIdxs,
		MessageInfos:      file_domain_billing_model_arrears_proto_msgTypes,
	}.Build()
	File_domain_billing_model_arrears_proto = out.File
	file_domain_billing_model_arrears_proto_rawDesc = nil
	file_domain_billing_model_arrears_proto_goTypes = nil
	file_domain_billing_model_arrears_proto_depIdxs = nil
}
