// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/blackhorseya/sion/app/domain/rental/repo/asset/irent"
	"github.com/blackhorseya/sion/entity/domain/rental/repo"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, error) {
	iAssetRepo, err := irent.NewAssetRepo()
	if err != nil {
		return nil, err
	}
	injector := &Injector{
		assets: iAssetRepo,
	}
	return injector, nil
}

// wire.go:

// Injector is the wire injector for the fetchAvailableCars job.
type Injector struct {
	assets repo.IAssetRepo
}
