// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package biz

import (
	"github.com/blackhorseya/irent/pkg/entity/domain/account/biz"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateBiz() biz.IBiz {
	iBiz := NewImpl()
	return iBiz
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
