// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package restful

import (
	"github.com/blackhorseya/sion/app/domain/rental/biz"
	"github.com/blackhorseya/sion/app/domain/rental/repo/asset/irent"
	"github.com/blackhorseya/sion/pkg/adapterx"
	"github.com/blackhorseya/sion/pkg/linebotx"
	"github.com/blackhorseya/sion/pkg/transports/httpx"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func New(v *viper.Viper) (adapterx.Servicer, error) {
	server, err := httpx.NewServer()
	if err != nil {
		return nil, err
	}
	messagingApiAPI, err := linebotx.NewClient()
	if err != nil {
		return nil, err
	}
	iAssetRepo, err := irent.NewAssetRepo()
	if err != nil {
		return nil, err
	}
	iRentalBiz := biz.NewRentalBiz(iAssetRepo)
	servicer := newService(server, messagingApiAPI, iRentalBiz)
	return servicer, nil
}

func NewRestful() (adapterx.Restful, error) {
	server, err := httpx.NewServer()
	if err != nil {
		return nil, err
	}
	messagingApiAPI, err := linebotx.NewClient()
	if err != nil {
		return nil, err
	}
	iAssetRepo, err := irent.NewAssetRepo()
	if err != nil {
		return nil, err
	}
	iRentalBiz := biz.NewRentalBiz(iAssetRepo)
	restful := newRestful(server, messagingApiAPI, iRentalBiz)
	return restful, nil
}

// wire.go:

var providerSet = wire.NewSet(httpx.NewServer, linebotx.NewClient, biz.ProviderSet)
