// Code generated by mockery v2.16.0. DO NOT EDIT.

package repo

import (
	contextx "github.com/blackhorseya/irent/pkg/contextx"
	mock "github.com/stretchr/testify/mock"

	model "github.com/blackhorseya/irent/pkg/entity/domain/account/model"
)

// MockIRepo is an autogenerated mock type for the IRepo type
type MockIRepo struct {
	mock.Mock
}

// GetMemberStatus provides a mock function with given fields: ctx, token
func (_m *MockIRepo) GetMemberStatus(ctx contextx.Contextx, token string) (*model.Profile, error) {
	ret := _m.Called(ctx, token)

	var r0 *model.Profile
	if rf, ok := ret.Get(0).(func(contextx.Contextx, string) *model.Profile); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Profile)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, id, password
func (_m *MockIRepo) Login(ctx contextx.Contextx, id string, password string) (*model.Profile, error) {
	ret := _m.Called(ctx, id, password)

	var r0 *model.Profile
	if rf, ok := ret.Get(0).(func(contextx.Contextx, string, string) *model.Profile); ok {
		r0 = rf(ctx, id, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Profile)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, string, string) error); ok {
		r1 = rf(ctx, id, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockIRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockIRepo creates a new instance of MockIRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockIRepo(t mockConstructorTestingTNewMockIRepo) *MockIRepo {
	mock := &MockIRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
