// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repo

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateRepo() IRepo {
	iRepo := NewImpl()
	return iRepo
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
