// Code generated by mockery v2.16.0. DO NOT EDIT.

package biz

import (
	contextx "github.com/blackhorseya/irent/pkg/contextx"
	mock "github.com/stretchr/testify/mock"

	model "github.com/blackhorseya/irent/pkg/entity/domain/account/model"

	ordermodel "github.com/blackhorseya/irent/pkg/entity/domain/order/model"

	rentalmodel "github.com/blackhorseya/irent/pkg/entity/domain/rental/model"
)

// MockIBiz is an autogenerated mock type for the IBiz type
type MockIBiz struct {
	mock.Mock
}

// BookRental provides a mock function with given fields: ctx, from, target
func (_m *MockIBiz) BookRental(ctx contextx.Contextx, from *model.Profile, target *rentalmodel.Car) (*ordermodel.Lease, error) {
	ret := _m.Called(ctx, from, target)

	var r0 *ordermodel.Lease
	if rf, ok := ret.Get(0).(func(contextx.Contextx, *model.Profile, *rentalmodel.Car) *ordermodel.Lease); ok {
		r0 = rf(ctx, from, target)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ordermodel.Lease)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, *model.Profile, *rentalmodel.Car) error); ok {
		r1 = rf(ctx, from, target)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CancelLease provides a mock function with given fields: ctx, from, target
func (_m *MockIBiz) CancelLease(ctx contextx.Contextx, from *model.Profile, target *ordermodel.Lease) error {
	ret := _m.Called(ctx, from, target)

	var r0 error
	if rf, ok := ret.Get(0).(func(contextx.Contextx, *model.Profile, *ordermodel.Lease) error); ok {
		r0 = rf(ctx, from, target)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetArrears provides a mock function with given fields: ctx, from, target
func (_m *MockIBiz) GetArrears(ctx contextx.Contextx, from *model.Profile, target *model.Profile) (*ordermodel.Arrears, error) {
	ret := _m.Called(ctx, from, target)

	var r0 *ordermodel.Arrears
	if rf, ok := ret.Get(0).(func(contextx.Contextx, *model.Profile, *model.Profile) *ordermodel.Arrears); ok {
		r0 = rf(ctx, from, target)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ordermodel.Arrears)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, *model.Profile, *model.Profile) error); ok {
		r1 = rf(ctx, from, target)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListLease provides a mock function with given fields: ctx, from
func (_m *MockIBiz) ListLease(ctx contextx.Contextx, from *model.Profile) ([]*ordermodel.Lease, error) {
	ret := _m.Called(ctx, from)

	var r0 []*ordermodel.Lease
	if rf, ok := ret.Get(0).(func(contextx.Contextx, *model.Profile) []*ordermodel.Lease); ok {
		r0 = rf(ctx, from)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ordermodel.Lease)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, *model.Profile) error); ok {
		r1 = rf(ctx, from)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Liveness provides a mock function with given fields: ctx
func (_m *MockIBiz) Liveness(ctx contextx.Contextx) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(contextx.Contextx) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Readiness provides a mock function with given fields: ctx
func (_m *MockIBiz) Readiness(ctx contextx.Contextx) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(contextx.Contextx) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockIBiz interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockIBiz creates a new instance of MockIBiz. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockIBiz(t mockConstructorTestingTNewMockIBiz) *MockIBiz {
	mock := &MockIBiz{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
